### ISSUE TITLE
Ejecutar guía de primeros pasos con MongoDB

### ISSUE THREAD

**Issue by olicrea** [olicrea/DEV013-burger-queen-api#3]
- [x] [1. Instalar MongoDB y Compass](https://github.com/olicrea/DEV013-burger-queen-api/blob/main/guides/GETTING-STARTED-MONGODB.md#1-instalar-mongodb-y-compass)

Usé: [] (https://www.youtube.com/watch?v=2cWZ0lFbJoY&t=145s)

- [x] [2. Levanta la base de datos y servidor](https://github.com/olicrea/DEV013-burger-queen-api/blob/main/guides/GETTING-STARTED-MONGODB.md#2-levanta-la-base-de-datos-y-servidor)
- [x] [3. Elegir módulo (cliente)](https://github.com/olicrea/DEV013-burger-queen-api/blob/main/guides/GETTING-STARTED-MONGODB.md#3-elegir-m%C3%B3dulo-cliente)
- [x] [4. Definir esquemas](https://github.com/olicrea/DEV013-burger-queen-api/blob/main/guides/GETTING-STARTED-MONGODB.md#4-definir-esquemas)
- [x] [5. Implementar los primeros TODOs](https://github.com/olicrea/DEV013-burger-queen-api/blob/main/guides/GETTING-STARTED-MONGODB.md#5-implementar-los-primeros-todos)
   - [x] To Do 1
   - [x] - [ ] To Do 2
             - [ ] (https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Classes/constructor)
   - [x] To Do 3
   - [x] To Do 4
   - [x] To Do 5
- [ ] [6. Definir estrategia de pruebas unitarias](https://github.com/olicrea/DEV013-burger-queen-api/blob/main/guides/GETTING-STARTED-MONGODB.md#6-definir-estrategia-de-pruebas-unitarias)
- [ ] [7. Familiarizarte con las pruebas de integración (e2e)](https://github.com/olicrea/DEV013-burger-queen-api/blob/main/guides/GETTING-STARTED-MONGODB.md#7-familiarizarte-con-las-pruebas-de-integraci%C3%B3n-e2e)

**Comment by olicrea** [comment]
5. Implementar los primeros TODOs:

- [ ] To Do 1
- [ ] To Do 2
- [ ] To Do 3
- [ ] To Do 4
- [ ] To Do 5
